version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: task_manager
      TZ: UTC
      PGTZ: UTC
    ports:
      - '54328:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "timezone=UTC"]

  app:
    build: .
    env_file: .env.docker
    environment:
      NODE_ENV: docker
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: sh -c "npm run start:dev"

volumes:
  pgdata: 